services:
  cqueue:
    build: .
    ports:
      - "${CQUEUE_PORT:-7705}:7705"
    volumes:
      - ${SOURCEROOT_PATH}:/repos/SourceRoot:rw
      - ${IUROOT_PATH}:/repos/IuRoot:rw
    user: "${UID:-501}:${GID:-20}"
    restart: unless-stopped
    env_file: ../.env
